apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - { name: PORT, value: "3460" }
            - { name: SHOPIFY_APP_URL, value: "https://skirmshop.e-dani.com/bundles" }
            - { name: SCOPES, value: "read_products,write_products,read_inventory,read_orders,write_app_proxy" }
            - { name: SHOPIFY_ALLOWED_SHOPS, value: "skirmshop-spain.myshopify.com" }
            - { name: SHOPIFY_APP_PROXY_MAX_AGE_SECONDS, value: "300" }
            - { name: STANDALONE_CONFIGURATOR_ENABLED, value: "false" }
          envFrom:
            - secretRef: { name: bundles-secrets }
